baseurl: ""
url: "https://ttyb.github.io"
# Build settings
markdown: kramdown
encoding: utf-8
permalink: /:categories/:title.html
gems: [jekyll-paginate]
# highlighter: rouge
kramdown:
  input: GFM 
  syntax_highlighter: rouge
