baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ttyb.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
encoding: utf-8
permalink: /:categories/:title.html
highlighter: rouge #  [rouge, pygments]
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil